### PR TITLE
Added five Social Connections

### PR DESCRIPTION
**Pull request by sareenasaji**

### CODE REVIEW

**Comment by kaarthikrajeev** [comment]
adding some hover animations would be nice.

**Comment by preveenraj** [comment]
I see that the top navbar links doesn't work. Are you already working on that?
If you are NOT planning to complete it now, you can just hide the links and come back to it later.

**Review by kaarthikrajeev — COMMENTED** [review]
`<i class="fab fa-instagram text-black text-2xl line-height-16 transition duration-300"></i>`
adding an hover:scale-110 would be nice

**Comment by sareenasaji** [comment]
> I see that the top navbar links doesn't work. Are you already working on that? If you are NOT planning to complete it now, you can just hide the links and come back to it later.

ok

**Pull request merged**
